### ISSUE TITLE
7.0 Update not in Dalamud?

### ISSUE THREAD

**Issue by gorbiWTF** [Lerofni/TooltipNotes#24]
Hey, I love your plug-in and I miss it.

I saw you added support for 7.0 but in Dalamud it says it's "outdated and incompatible".

Am I missing something?

**Comment by Lerofni** [comment]
You may have to enable Testing by right clicking the plugin as the only 7.0 compatible version is in testing

**Comment by gorbiWTF** [comment]
Ah, I didn't know this was a thing lol
I enabled it in the settings and installed the testing version. Works perfectly now, thank you!
